### PR TITLE
Remove old log files

### PR DESCRIPTION
**Pull request by ammongit**
These shouldn't be in the source, and haven't been touched for years anyways.

### CODE REVIEW

**Comment by rossjrw** [comment]
logs/jobs.log is used by bin/job.php and has logs from this April - are we sure it's unused? Do we know what bin/job.php does?

**Comment by ammongit** [comment]
If we keep the directory it should be fully `.gitignore`'d, logs shouldn't be in the repo still. It's runtime stuff that's not relevant to some arbitrary person running the code.

**Review by rossjrw — APPROVED** [review]
Should this be in the main gitignore

**Comment by ammongit** [comment]
thanks @rossjrw

**Pull request merged**
