### PR TITLE
Reorganize some client/* folders into misc/*

### PR DESCRIPTION
**Pull request by Monkatraz**
This cleans up the root level of `client/` a little bit. Also, linting tools will ignore the `misc/` folder.

### CODE REVIEW

**Comment by emmiegit** [comment]
Does "dev" here mean "local"? I remember discussing using the latter term to avoid confusion with the "dev" environment (https://www.wikijump.dev/)

**Comment by Monkatraz** [comment]
Uh, no, in this context it means "development resources". If you have a better name, I'm welcome to hear it.

**Comment by emmiegit** [comment]
Maybe `developers/`? Or `develop/` similar to the branch name?

**Comment by Monkatraz** [comment]
I'm not sure if lengthening the name adds anything substantive - plus it just makes typing out directories a little more verbose, lol. It would have to be something like `resources/`, although that implies assets, which is why I didn't choose that.

**Comment by emmiegit** [comment]
The other name I was thinking of was `install/`, but like `resources/` that doesn't really fit.

Maybe `templates/` would be better here? At least for the stuff you have to copy, then `docs/` remains where it is.

**Comment by Monkatraz** [comment]
Well, `types/` goes in there too - they don't fit into any other directory (except maybe as a weird, hardcoded module).

**Comment by Monkatraz** [comment]
I do expect more to eventually go into this folder, maybe `examples/`, or maybe even configuration settings. It's kind of a dumping ground for misc. monorepo stuff that isn't directly part of packages.

**Comment by emmiegit** [comment]
Then `misc/`? lol

I just don't really want `dev` confusion as discussed, basically any other name would be fine with me.

**Comment by Monkatraz** [comment]
yeah you know what `misc/` does fit. we've successfully talked the solution out of myself

**Review by emmiegit — APPROVED** [review]

**Review by rossjrw — APPROVED** [review]

**Pull request merged**
