### PR TITLE
Add all the Korean translations (fluent)

### PR DESCRIPTION
**Pull request by Denevola**
Translated all files under the `locales/fluent` directory into Korean.

### CODE REVIEW

**Review by emmiegit — APPROVED** [review]
Everything seems to look fine to me, thanks for the contribution!

**Comment by Denevola** [comment]
@emmiegit I have a question about contributing.

Is it okay to translate `locales/cmftml` as well? I wasn't sure since there are no translations yet and the locales validator doesn't support it.

**Comment by emmiegit** [comment]
@Denevola You could I suppose, but I think we should wait until those are more set in stone first

**Comment by Denevola** [comment]
I understood, thanks.

**Pull request merged**
