### PR TITLE
Remove remaining uses of the old local domain

### PR DESCRIPTION
**Pull request by emmiegit**
This PR fixes up some remaining occurrences of `wikijump.test`. This also changes the variables in the containers, which caused issues with local deployment.

### CODE REVIEW

**Comment by emmiegit** [comment]
@Monkatraz Given that `development.md` wasn't updated in your PR, and they contained those large bits of duplicated instructions between them, to what extent should we merge or delegate those documents?

**Comment by Monkatraz** [comment]
I'm not sure. I think that `development.md` should probably be very backend focused. I think it's okay if info is duplicated as long as if comes from different contexts.

**Review by Monkatraz — APPROVED** [review]

**Comment by emmiegit** [comment]
Then I feel like it would make sense to rename it to `development.md`?

But honestly, you need to have the frontend working even if you're only changing the PHP, so wouldn't I need to follow the same instructions there?

Or perhaps:
* `development.md` -- minimal doc that describes basic local deployment, frontend and backend
* `frontend.md` -- describes things specific to frontend not needed if you're not touching it
* `backend.md` -- ditto for backend

**Comment by Monkatraz** [comment]
Yeah, something like that sounds fine. I do think that have one cohesive guide rather than it split into multiple files is better, but it doesn't matter that much.

**Comment by emmiegit** [comment]
Okay, in that case I prefer the one cohesive `development.md` that covers everything. Would you be able to do that sometime, since you wrote the frontend doc?

**Comment by emmiegit** [comment]
thanks @Monkatraz

**Comment by Monkatraz** [comment]
> Okay, in that case I prefer the one cohesive `development.md` that covers everything. Would you be able to do that sometime, since you wrote the frontend doc?

Yeah, I'll get to it sooner or later, probably whenever I need to touch the docs folder again (probably won't be long lol)

**Pull request merged**
