### PR TITLE
Add enum abstract class

### PR DESCRIPTION
**Pull request by emmiegit**
Based on the solution [here](https://stackoverflow.com/questions/254514/enumerations-on-php/17045081#17045081), it will allow us to make enums in PHP using class constants.

An example enumeration using this code:

```php
use \Wikijump\Common\Enum;

final class ResponseStatusCode extends Enum
{
    const OK                         = 200;
    const CREATED                    = 201;
    const ACCEPTED                   = 202;
    // ...
    const SERVICE_UNAVAILABLE        = 503;
    const GATEWAY_TIME_OUT           = 504;
    const HTTP_VERSION_NOT_SUPPORTED = 505;
}
```

### CODE REVIEW

**Review by Monkatraz — APPROVED** [review]
```php
final class ResponseStatusCode extends Enum
{

    const OK                         = 200;
    const CREATED                    = 201;
    const ACCEPTED                   = 202;
    // ...
    const SERVICE_UNAVAILABLE        = 503;
    const GATEWAY_TIME_OUT           = 504;
    const HTTP_VERSION_NOT_SUPPORTED = 505;

}
```
It's wonderful to know that PHP is dealing with the _exact same issues_ TypeScript deals with! this is a really nice and slick solution for this problem though

EDIT: Just for kicks, here is how TypeScript transforms its enums:
```ts
enum Enum {
  A,
}

let a = Enum.A;
let nameOfA = Enum[a]; // "A"
```
```js
var Enum;
(function (Enum) {
    Enum[Enum["A"] = 0] = "A";
})(Enum || (Enum = {}));
let a = Enum.A;
let nameOfA = Enum[a]; // "A"
```

It's kind of horrifying. If it's a `const` enum they'd actually get compiled out, but with `isolatedModules` (which is nigh-required nowadays due to build tools) `const` enums don't do anything.

**Comment by emmiegit** [comment]
I thought Typescript did have enums though, I could've sworn I've used them before.

**Comment by Monkatraz** [comment]
> I thought Typescript did have enums though, I could've sworn I've used them before.

Yeah it does, but they're fake. You often don't see them used because people don't trust them - and the fact that you can implement 90% of their functionality using the following:
```ts
const Enum = {
  Type1: 1,
  Type2: 2
} as const

function takesEnum(input: keyof Enum) {
  // blegh
}
```

Now is that verbose and not as nice as the actual `enum` syntax? Totally - but people just don't use them even though they really should...

**Comment by emmiegit** [comment]
thanks @Monkatraz

**Pull request merged**
